# Generated by Django 5.0.6 on 2024-05-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.FileField(upload_to="photos/products"),
        ),
    ]
