# Generated by Django 5.0.6 on 2024-05-10 20:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_product_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="images",
            new_name="product_image",
        ),
    ]
